# Generated by Django 4.2.3 on 2023-07-14 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_studentmodel_user_teachermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
    ]
